package Smash::Global;

use strict;
use warnings;

our $SMASH_SCRIPT_NAME;
our $SMASH_SCRIPT_LOCATION;
our $SMASH_PERL;
our $NCBI_TAXONOMY_REMOTE_LOCATION;
our $TAXONOMY_LOCAL_LOCATION;

use base 'Exporter';
our @EXPORT_OK = qw($SMASH_SCRIPT_NAME $SMASH_SCRIPT_LOCATION $SMASH_PERL $NCBI_TAXONOMY_REMOTE_LOCATION $TAXONOMY_LOCAL_LOCATION);
our %EXPORT_TAGS = ('all' => [@EXPORT_OK]);

1;
